package com.example.mits_kids_youtube

import io.flutter.embedding.android.FlutterActivity
import io.flutter.embedding.engine.FlutterEngine
import io.flutter.plugin.common.MethodChannel
import android.view.KeyEvent
import com.mitskids.offline.PlaybackKeyLock
import com.mitskids.offline.ScreenOffRecoveryController
import com.mitskids.offline.PlaybackImmersiveController

class MainActivity : FlutterActivity() {
    private val playbackKeyLock = PlaybackKeyLock()
    private var playbackControlsChannel: MethodChannel? = null
    private var screenOffRecovery: ScreenOffRecoveryController? = null
    private var playbackImmersive: PlaybackImmersiveController? = null

    override fun configureFlutterEngine(flutterEngine: FlutterEngine) {
        super.configureFlutterEngine(flutterEngine)
        flutterEngine.plugins.add(com.mitskids.offline.OfflineMediaPlugin())
        flutterEngine.plugins.add(com.mitskids.offline.ParentSecurityPlugin())
        flutterEngine.plugins.add(com.mitskids.offline.BackupPlugin())
        flutterEngine.plugins.add(com.mitskids.offline.DownloadJobPlugin())
        flutterEngine.plugins.add(com.mitskids.offline.SeekPreviewPlugin())
        screenOffRecovery?.close()
        screenOffRecovery = ScreenOffRecoveryController(this, flutterEngine.dartExecutor.binaryMessenger)
        playbackImmersive?.close()
        playbackImmersive = PlaybackImmersiveController(window)
        playbackControlsChannel?.setMethodCallHandler(null)
        playbackControlsChannel = MethodChannel(flutterEngine.dartExecutor.binaryMessenger,
            "mits_kids/playback_controls").also { channel ->
            channel.setMethodCallHandler { call, result ->
                if (call.method == "setLockedPresentation") {
                    val locked = (call.arguments as? Map<*, *>)?.get("locked") as? Boolean
                    if (locked == null) {
                        playbackImmersive?.setLocked(false)
                        result.success(false)
                    } else result.success(playbackImmersive?.setLocked(locked) == true)
                } else if (call.method != "setTouchLocked") {
                    result.notImplemented()
                } else {
                    val locked = (call.arguments as? Map<*, *>)?.get("locked") as? Boolean
                    playbackKeyLock.focusChanged(hasWindowFocus())
                    if (locked == null) {
                        playbackKeyLock.setTouchLocked(false)
                        result.success(false)
                    } else result.success(playbackKeyLock.setTouchLocked(locked))
                }
            }
        }
    }

    override fun dispatchKeyEvent(event: KeyEvent): Boolean {
        // The OS keeps power, Home, system navigation and reserved combinations.
        // Consume only ordinary volume events actually delivered to this window.
        if (hasWindowFocus() && playbackKeyLock.consumes(event.keyCode, event.action,
                event.metaState != 0)) return true
        return super.dispatchKeyEvent(event)
    }

    override fun onResume() {
        super.onResume()
        playbackKeyLock.resume()
        playbackKeyLock.focusChanged(hasWindowFocus())
        playbackImmersive?.onResume()
        playbackImmersive?.onFocusChanged(hasWindowFocus())
        screenOffRecovery?.onResume()
        screenOffRecovery?.onFocusChanged(hasWindowFocus())
    }

    override fun onPause() {
        playbackImmersive?.onPause()
        screenOffRecovery?.onPause()
        playbackKeyLock.pause()
        super.onPause()
    }

    override fun onWindowFocusChanged(hasFocus: Boolean) {
        playbackKeyLock.focusChanged(hasFocus)
        // Queue Flutter's lifecycle transition before the recovery callback
        // generated by the same focus return, as onResume already does.
        super.onWindowFocusChanged(hasFocus)
        playbackImmersive?.onFocusChanged(hasFocus)
        screenOffRecovery?.onFocusChanged(hasFocus)
    }

    override fun onUserLeaveHint() {
        playbackImmersive?.onUserLeaveHint()
        screenOffRecovery?.onUserLeaveHint()
        super.onUserLeaveHint()
    }

    override fun onStop() {
        playbackImmersive?.onStop()
        screenOffRecovery?.onStop()
        super.onStop()
    }

    override fun cleanUpFlutterEngine(flutterEngine: FlutterEngine) {
        playbackImmersive?.close()
        playbackImmersive = null
        screenOffRecovery?.close()
        screenOffRecovery = null
        playbackKeyLock.detach()
        playbackControlsChannel?.setMethodCallHandler(null)
        playbackControlsChannel = null
        super.cleanUpFlutterEngine(flutterEngine)
    }

    override fun onDestroy() {
        playbackImmersive?.close()
        playbackImmersive = null
        screenOffRecovery?.close()
        screenOffRecovery = null
        playbackKeyLock.detach()
        playbackControlsChannel?.setMethodCallHandler(null)
        playbackControlsChannel = null
        super.onDestroy()
    }
}
